# Builds the drawserver. This server runs the java app that will build the draw
# eventually. Note that the draw is produced in the daoserver currently

FROM tomcat:8.0
MAINTAINER Robert Higgins <robert.h.higgins@gmail.com>

ADD drawbuilder/target/drawbuilder.war webapps/
