alias psql-db='PGPASSWORD=$DB_PASSWORD psql -h $DB_PORT_5432_TCP_ADDR -p $DB_PORT_5432_TCP_PORT -d docker -U docker'
alias players='psql-db -c "select * from player;"'
alias accounts='psql-db -c "select * from account;"'
alias tournaments='psql-db -c "select * from tournament;"'
