dao-get () {
    curl "http://$DAOSERVER_PORT_5000_TCP_ADDR:$DAOSERVER_PORT_5000_TCP_PORT/$1"
}
dao-post () {
    curl --data $2 "http://$DAOSERVER_PORT_5000_TCP_ADDR:$DAOSERVER_PORT_5000_TCP_PORT/$1"
}
