#! /bin/bash

printf "\n\nRunning smoke tests for Tournament Organiser Webserver\n\n"

# Front page
printf "\nTesting front page\n"
front_page_status=$(curl -sL -w "%{http_code}" http://$WEBSERVER_PORT_5000_TCP_ADDR:$WEBSERVER_PORT_5000_TCP_PORT -o /dev/null)
if [ "$front_page_status" -ne "200" ]; then
    echo "Smoke test failed - the front page returned code $front_page_status"
fi

# Hooray
printf "\n\nSmoke test Passed\n\n"
