#! /bin/bash

if [ ! -f docker-compose.yml ]; then
    echo "Compose File Not Found!"
    exit 2
fi

# Remove all containers and get a basic install up
# Where should build output be funnelled?
ENV=${1:-"prod"}
if [ "$ENV" == 'dev' ]; then
    docker-compose kill &> /dev/null
    docker-compose rm -f &> /dev/null

    docker-compose pull  &> /dev/null
    docker-compose build &> /dev/null
else

    docker-compose kill
    docker-compose rm -f

    docker-compose pull
    docker-compose build
fi
