#! /bin/bash

if [ ! -f docker-compose.yml ]; then
    echo "Compose File Not Found!"
    exit 2
fi

# Remove all containers and get a basic install up

docker-compose kill     &> /dev/null
docker-compose rm -f    &> /dev/null

docker-compose pull     &> /dev/null
docker-compose build    &> /dev/null

docker-compose up -d database daoserver webserver node &> /dev/null
