#! /bin/bash
pylint $(find . -iname "*.py")
eslint node test/dao/functionality

# Build all containers and run all tests
cp config/dev/docker-compose.yml docker-compose.yml
cp config/dev/docker-passwords.yml docker-passwords.yml
./scripts/install dev

sleep 10

# Add some data to database for use in browser
bash scripts/insert_into_db database database/data/dev/basic_functions.sql
bash scripts/insert_into_db database database/data/dev/behaviour_test_data.sql
