#! /bin/bash

SYSTEMS="database daoserver webserver"
UPDATE=${1:-"no"}

if [ "$UPDATE" == '--update' ]; then
    shift

    docker-compose up -d webserver

else

    ./scripts/get-compose-files --dev
    ./scripts/clean-and-build --dev $SYSTEMS

    docker-compose up -d $SYSTEMS &> /dev/null

    # Add some data to database for use in browser
    docker exec daoserver bash -c '/webapp/wait-for-postgres.sh database bash'
    bash scripts/insert_into_db database database/data/dev/basic_functions.sql
    bash scripts/insert_into_db database database/data/dev/web_functionality_test_data.sql

fi
