#! /bin/bash

SYSTEMS="systemtestdb systemtestdaoserver systemtestnode"
TEST_SYSTEMS="systemtest_functionality systemtest_usability"
# Build all containers and run all tests
cp config/dev/docker-compose.yml docker-compose.yml
cp config/dev/docker-passwords.yml docker-passwords.yml
docker-compose kill     &> /dev/null
docker-compose rm -f    &> /dev/null

docker-compose pull $SYSTEMS $TEST_SYSTEMS  &> /dev/null
docker-compose build $SYSTEMS $TEST_SYSTEMS &> /dev/null
docker-compose up -d $SYSTEMS               &> /dev/null

docker exec systemtestdaoserver bash -c '/webapp/wait-for-postgres.sh systemtestdb bash'
bash scripts/insert_into_db systemtestdb database/data/dev/basic_functions.sql
bash scripts/insert_into_db systemtestdb database/data/dev/behaviour_test_data.sql

docker-compose run systemtest_functionality
docker-compose run systemtest_usability
