#! /bin/bash

# Build all containers and run all tests
cp config/dev/docker-compose.dev.yml docker-compose.yml
cp config/dev/docker-passwords.dev.yml docker-passwords.yml
./scripts/install
docker-compose up -d apitestdb apitestdaoserver &> /dev/null
docker-compose up -d systemtestdb systemtestdaoserver systemtestwebserver &> /dev/null

docker-compose run unittest

# API Tests
bash scripts/insert_into_db apitestdb database/data/dev/basic_functions.sql
bash scripts/insert_into_db apitestdb database/data/dev/api_test_data.sql
docker-compose run apitest

# System Tests
bash scripts/insert_into_db systemtestdb database/data/dev/basic_functions.sql
bash scripts/insert_into_db systemtestdb database/data/dev/behaviour_test_data.sql
docker-compose run systemtest


pylint $(find . -iname "*.py")
