#! /bin/bash

# Build all containers and run all tests
./scripts/install config/dev/docker-compose.dev.yml

docker-compose run daoserver python -m unittest discover -s unit_tests \
    --pattern=*.py


docker exec -it database bash -c 'psql --file=/docker-entrypoint-initdb.d/data/dev/behaviour_test_data.sql -d "$POSTGRES_DB" -U "$POSTGRES_USER" '
docker-compose run apitest
docker-compose run systemtest


pylint $(find . -iname "*.py")
