#! /bin/bash
./scripts/get-compose-files --dev
./scripts/clean-and-build --dev

docker-compose up -d unittestdb &> /dev/null &
docker-compose up -d apitestdb apitestdaoserver &> /dev/null &
docker-compose up -d systemtestdb systemtestdaoserver systemtestwebserver &> /dev/null &

wait

./scripts/lint

docker-compose run unittest

# API Tests
bash scripts/insert_into_db apitestdb database/data/dev/basic_functions.sql
bash scripts/insert_into_db apitestdb database/data/dev/api_test_data.sql
docker-compose run apitest

# System Tests
bash scripts/insert_into_db systemtestdb database/data/dev/basic_functions.sql
bash scripts/insert_into_db systemtestdb database/data/dev/behaviour_test_data.sql
docker-compose run systemtest_functionality
docker-compose run systemtest_usability
