#! /bin/bash

SYSTEMS="unittestdb unittest"
# Build all containers and run all tests
cp config/dev/docker-compose.dev.yml docker-compose.yml
cp config/dev/docker-passwords.dev.yml docker-passwords.yml
docker-compose kill  &> /dev/null
docker-compose rm -f &> /dev/null

docker-compose pull  $SYSTEMS &> /dev/null
docker-compose build $SYSTEMS &> /dev/null
docker-compose up -d unittestdb &> /dev/null

docker-compose run unittest
