#! /bin/bash

HAS_ERROR=""

printf "\n\nRunning smoke tests for Tournament Organiser Webserver\n\n"

# Front page
printf "Testing Front Page\n"
front_page_status=$(curl -sL -w "%{http_code}" -H "Host: 172.81.179.42" http://$WEBSERVER_PORT_8000_TCP_ADDR:$WEBSERVER_PORT_8000_TCP_PORT -o /dev/null)
if [ "$front_page_status" -ne "200" ]; then
    echo "Smoke test failed - the front page returned code $front_page_status"
    HAS_ERROR="true"
fi

# DAO Server
printf "Testing that the DAO Server exists\n"
front_page_status=$(curl -sL -w "%{http_code}" http://$DAOSERVER_PORT_5000_TCP_ADDR:$DAOSERVER_PORT_5000_TCP_PORT -o /dev/null)
if [ "$front_page_status" -ne "200" ]; then
    echo "Smoke test failed - the front page returned code $front_page_status"
    HAS_ERROR="true"
fi


# DB Connection from the daoserver
printf "Testing DB Connection from the daoserver\n"
db_has_version=$(PGPASSWORD=$DATABASE_PASSWORD psql -h $DATABASE_PORT_5432_TCP_ADDR -p $DATABASE_PORT_5432_TCP_PORT -d $POSTGRES_DB -U $POSTGRES_USER -c "select version();")
if [ -z "$db_has_version" ]; then
    echo "Smoke test failed - the connection to the db returned $db_has_version"
    HAS_ERROR="true"
fi


# Hooray
if [ -z "$HAS_ERROR" ]; then
    printf "\n\nSmoke test Passed\n\n"
    exit 0
fi

printf "\n\nSmoke test Failed!\n\n"
exit 1
